"""Generate HaloAP_launcher/Data/mission_order.h from the apworld's mission data.

    python3 tools/gen_mission_tables.py

For each game: its missions in play/menu order (the DLL reports mission unlocks and
completions by index), each mission's map name (what the DLL reports when a mission is
running), and every chapter key the DLL can report mapped to its location ID. Chapter keys
are the title index (H2, H3, H4) or the chapter's runtime string_id (Reach; resolved from
each map's string table, see Docs/hook-map-h2-h3-h4-reach.md and reach_chapter_sids.json).
Rerun after changing apworld/halo_mcc/data/missions.py.
"""
import ast
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MISSIONS_PY = os.path.join(ROOT, "apworld/halo_mcc/data/missions.py")
REACH_SIDS = os.path.join(ROOT, "tools/reach_chapter_sids.json")
OUT = os.path.join(ROOT, "HaloAP_launcher/Data/mission_order.h")

CHAPTER_OFFSET = 10
SKULL_LOCATION_OFFSET = 20
# Games with a location for loading into each playable mission (levels.py MISSION_START_GAMES)
MISSION_START_GAMES = {"h4"}

CE = [("The Pillar of Autumn", "a10"), ("Halo", "a30"), ("The Truth and Reconciliation", "a50"),
      ("The Silent Cartographer", "b30"), ("Assault on the Control Room", "b40"),
      ("343 Guilty Spark", "c10"), ("The Library", "c20"), ("Two Betrayals", "c40"),
      ("Keyes", "d20"), ("The Maw", "d40")]
GAMES = [("h2a", 2, "H2_MISSIONS"), ("h3", 3, "H3_MISSIONS"), ("h4", 4, "H4_MISSIONS"),
         ("reach", 6, "REACH_MISSIONS")]


def literal(node):
    return ast.literal_eval(node)


def parse_skulls(tree):
    """SKULL_PICKUPS: {game: {map: (S(name, key), ...)}}"""
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and getattr(node.target, "id", "") == "SKULL_PICKUPS":
            skulls = {}
            for game_key, by_map in zip(node.value.keys, node.value.values):
                skulls[literal(game_key)] = {
                    literal(map_key): [(literal(c.args[0]), literal(c.args[1])) for c in entries.elts]
                    for map_key, entries in zip(by_map.keys, by_map.values)}
            return skulls
    raise SystemExit("SKULL_PICKUPS not found")


def parse_missions():
    tree = ast.parse(open(MISSIONS_PY).read())
    lists = {}
    for node in tree.body:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            target = node.target if isinstance(node, ast.AnnAssign) else node.targets[0]
            if isinstance(target, ast.Name) and target.id.endswith("_MISSIONS"):
                missions = []
                for call in node.value.elts:
                    name, map_name = literal(call.args[0]), literal(call.args[1])
                    chapters = []
                    if len(call.args) > 2:
                        for ch in call.args[2].elts:
                            chapters.append((literal(ch.args[0]), literal(ch.args[1])))
                    cinematic = any(k.arg == "cinematic" and literal(k.value) for k in call.keywords)
                    missions.append((name, map_name, chapters, cinematic))
                lists[target.id] = missions
    return lists, parse_skulls(tree)


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    lists, skulls = parse_missions()
    reach_sids = json.load(open(REACH_SIDS))
    out = [
        "#pragma once",
        "",
        "// Generated by tools/gen_mission_tables.py from apworld/halo_mcc/data/missions.py.",
        "// Don't edit by hand.",
        "",
        "#include <cstdint>",
        "#include <string>",
        "#include <vector>",
        "",
        "namespace haloap {",
        "",
        "    struct ChapterKeyDef {",
        "        uint32_t key;        // title index (H2/H3/H4) or runtime string_id (Reach)",
        "        int64_t locationId;",
        "        const char* name;",
        "    };",
        "",
        "    struct MissionDef {",
        "        std::string name;    // level name without the game prefix",
        "        const char* map;     // map name the DLL reports",
        "        int64_t startLocationId;  // 0: no mission-start location",
        "        std::vector<ChapterKeyDef> chapters;",
        "        std::vector<ChapterKeyDef> skulls;  // key: what the DLL reports; 0xFFFFFFFF matches any",
        "    };",
        "",
        "    struct GameMissionOrder {",
        "        const char* key;   // apworld game key, as used in slot data",
        "        int code;          // apworld / DLL game code",
        "        std::vector<MissionDef> missions;  // play order = MCC menu order",
        "    };",
        "",
        "    inline const std::vector<GameMissionOrder>& GetGameMissionOrders() {",
        "        static const std::vector<GameMissionOrder> orders = {",
    ]
    out.append('            {"ce", 1, {')
    for name, map_name in CE:
        out.append(f"                {{{cstr(name)}, {cstr(map_name)}, 0, {{}}, {{}}}},")
    out.append("            }},")
    for key, code, list_name in GAMES:
        out.append(f'            {{"{key}", {code}, {{')
        for number, (name, map_name, chapters, cinematic) in enumerate(lists[list_name], start=1):
            offset = code * 100000 + number * 1000
            start = offset + CHAPTER_OFFSET if key in MISSION_START_GAMES and not cinematic else 0
            entries = []
            for n, (chapter, keys) in enumerate(chapters, start=1):
                keys = keys if isinstance(keys, tuple) else (keys,)
                for k in keys:
                    if isinstance(k, str):
                        k = reach_sids[map_name][k]
                    entries.append(f"{{{k}u, {offset + CHAPTER_OFFSET + n}, {cstr(chapter)}}}")
            out.append(f"                {{{cstr(name)}, {cstr(map_name)}, {start}, {{")
            for e in entries:
                out.append(f"                    {e},")
            out.append("                }, {")
            for n, (skull, k) in enumerate(skulls.get(key, {}).get(map_name, []), start=1):
                out.append(f"                    {{{k & 0xFFFFFFFF}u, {offset + SKULL_LOCATION_OFFSET + n}, "
                           f"{cstr(skull + ' Skull')}}},")
            out.append("                }},")
        out.append("            }},")
    out += ["        };", "        return orders;", "    }", "", "}  // namespace haloap", ""]
    open(OUT, "w").write("\n".join(out))
    print("wrote", OUT)


main()
